"""new new

Revision ID: 726b96b17652
Revises: e90316b396bb
Create Date: 2023-07-13 03:36:08.538026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726b96b17652'
down_revision = 'e90316b396bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_events_created_by_users', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_calendar_events_created_by_users', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
