"""updates models.py

Revision ID: 7b35f220db54
Revises: f3be319a0b20
Create Date: 2023-06-26 14:50:08.271207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b35f220db54'
down_revision = 'f3be319a0b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placeholder', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inputs', schema=None) as batch_op:
        batch_op.drop_column('placeholder')

    # ### end Alembic commands ###
