"""new new

Revision ID: e90316b396bb
Revises: ecc8d5564183
Create Date: 2023-07-13 03:34:25.394215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90316b396bb'
down_revision = 'ecc8d5564183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_calendar_events_created_by_users'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_calendar_events_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
