"""ugh

Revision ID: f71757bcfef7
Revises: cb8b12b9305a
Create Date: 2023-07-13 15:41:51.143178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71757bcfef7'
down_revision = 'cb8b12b9305a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_calendar_events_created_by_users'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('user_calendar_event_association', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('calendar_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_calendar_event_association', schema=None) as batch_op:
        batch_op.alter_column('calendar_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_calendar_events_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
